#!/bin/bash
set -eu

readonly dirnames=$(find . -mindepth 1 -maxdepth 1 -type d | sort)

changes=0

for d in $dirnames; do
  rd=$(realpath "$d")
  if [[ ! -z $(git -C "$rd" status --porcelain) ]]; then
    echo "$d"
    git -C "$rd" status --short
    changes=1
  fi
done

if [[ $changes -eq 0 ]]; then
  echo "No changes found under: $(pwd)"
fi 

