#!/bin/bash

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Usage:  ${0##*/} [directory] [noupdate]
    directory  directory to copy missing git modules from, instead of cloning
    noupdate   don't update modules except if they are missing"
  exit
fi

while [ -n "$1" ]; do
  if [ $1 = noupdate ]; then
    NOPULL=1
  else
    [ -d $1 ] || { echo "Directory not found: $1"; exit; }
    COPY_FROM=$1
  fi
  shift
done

if [ -z "$NOPULL" ]; then
  #---- Update all modules ----
  for i in ./* ; do
    if [ -d "$i" ]; then
      directory=$(basename $i)
      cd $directory
      git pull
      cd ..
    fi
  done
fi

#---- Get any URL translation ----
insteadof=$(git config --get-regexp 'url.*\.insteadof')
if [ -n "$insteadof" ]; then
  url=$(echo $insteadof | sed 's/^url\.\(.*\)\.insteadof .*/\1/')
  insteadof=$(echo $insteadof | sed 's/^.*\.insteadof //')
fi

#---- Check out any modules that we have not yet got ----
[ -f project.inc ] && project_inc=0
[ -f toolchain.pri ] && toolchain_pri=0
for i in ./* ; do
  if [ -d "$i" ]; then

    cd $(basename $i)

    submodules="submodules.pri"
    if [ -e "$submodules" ]; then

      remote=$(git config --get remote.origin.url | sed "s#^$insteadof#$url#")
      remote=${remote%/*}
      
      #---- Special case for tdp_build ----
      if [ ! -d "../tdp_build" ]; then
        cd ../
        if [ -n "$COPY_FROM" ] && [ -d $COPY_FROM/tdp_build ]; then
          cp -rp $COPY_FROM/tdp_build .
        else
          git "clone" "$remote/tdp_build.git"
        fi
        cd $(basename $i)
      fi
      
      #---- Copy project.inc into top level directory ----
      if [ -f project.inc ]; then
        if [ ! -f ../project.inc ]; then
          cp project.inc ../
          project_inc=1
        elif [ "$project_inc" = 1 ]; then
          echo "Error! project.inc found in more than one sub-directory"
          project_inc=2
        fi
      fi
      
      #---- Copy toolchain.pri into top level directory ----
      if [ -f toolchain.pri ]; then
        if [ ! -f ../toolchain.pri ]; then
          cp toolchain.pri ../
          toolchain_pri=1
        elif [ "$toolchain_pri" = 1 ]; then
          echo "Error! toolchain.pri found in more than one sub-directory"
          toolchain_pri=2
        fi
      fi

      exec<$submodules
      while read line
      do
        if [[ $line == SUBDIRS* ]]; then
        IFS='=' read -a arr <<< "$line"
        for item in "${arr[@]:1}"
        do
          item=$(echo "$item" | tr -d ' ')
          if [ ! -d "../$item" ]; then
            cd ../
            if [ -n "$COPY_FROM" ] && [ -d $COPY_FROM/$item ]; then
              cp -rp $COPY_FROM/$item .
            else
              git "clone" "$remote/$item.git"
            fi
            cd $(basename $i)
          fi
        done
        fi
      done
    fi

    cd ..
  fi
done

[ "$project_inc" = 2 ] && rm -f project.inc
[ "$toolchain_pri" = 2 ] && rm -f toolchain.pri

exit 0
